# Generated by Django 3.0.8 on 2020-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_ubicacioncomisaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacioncomisaria',
            name='CPNP',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacioncomisaria',
            name='GPS',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacioncomisaria',
            name='INEI',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacioncomisaria',
            name='TIPO',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
