# Generated by Django 3.0.8 on 2020-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0003_auto_20200708_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacioncomisaria',
            name='COMISARIA',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
