# Generated by Django 3.0.8 on 2020-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0007_auto_20200708_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionComisaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INEI', models.CharField(blank=True, max_length=200, null=True)),
                ('CPNP', models.CharField(blank=True, max_length=200, null=True)),
                ('NOMBREDD', models.CharField(blank=True, max_length=200, null=True)),
                ('NOMBREPP', models.CharField(blank=True, max_length=200, null=True)),
                ('NOMBREDI', models.CharField(blank=True, max_length=200, null=True)),
                ('GPS', models.CharField(blank=True, max_length=200, null=True)),
                ('MACREGPOL', models.CharField(blank=True, max_length=200, null=True)),
                ('REGPOL', models.CharField(blank=True, max_length=200, null=True)),
                ('DIVPOL', models.CharField(blank=True, max_length=200, null=True)),
                ('COMISARIA', models.CharField(blank=True, max_length=200, null=True)),
                ('TIPO', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UbicacionComisarias',
        ),
    ]
